export interface RickshawStand {
  id: number;
  name: string;
  namebn: string;
  lat: number;
  lng: number;
  waitTime: string;
  area: string;
}

export const RICKSHAW_STANDS: RickshawStand[] = [
  {
    id: 1,
    name: "Sadarghat",
    namebn: "সদরঘাট",
    lat: 23.7104,
    lng: 90.4074,
    waitTime: "1-3 min",
    area: "Old Dhaka",
  },
  {
    id: 2,
    name: "Gulshan 1 Circle",
    namebn: "গুলশান ১ সার্কেল",
    lat: 23.7808,
    lng: 90.4143,
    waitTime: "2-5 min",
    area: "Gulshan",
  },
  {
    id: 3,
    name: "Dhanmondi 27",
    namebn: "ধানমন্ডি ২৭",
    lat: 23.7461,
    lng: 90.3742,
    waitTime: "1-5 min",
    area: "Dhanmondi",
  },
  {
    id: 4,
    name: "New Market",
    namebn: "নিউ মার্কেট",
    lat: 23.733,
    lng: 90.386,
    waitTime: "1-2 min",
    area: "New Market",
  },
  {
    id: 5,
    name: "Farmgate",
    namebn: "ফার্মগেট",
    lat: 23.758,
    lng: 90.3893,
    waitTime: "3-7 min",
    area: "Tejgaon",
  },
  {
    id: 6,
    name: "Mohammadpur",
    namebn: "মোহাম্মদপুর",
    lat: 23.7631,
    lng: 90.356,
    waitTime: "3-8 min",
    area: "Mohammadpur",
  },
  {
    id: 7,
    name: "Mirpur 10",
    namebn: "মিরপুর ১০",
    lat: 23.8057,
    lng: 90.3668,
    waitTime: "2-4 min",
    area: "Mirpur",
  },
  {
    id: 8,
    name: "Motijheel",
    namebn: "মতিঝিল",
    lat: 23.728,
    lng: 90.4187,
    waitTime: "2-5 min",
    area: "Motijheel",
  },
  {
    id: 9,
    name: "Banani 11",
    namebn: "বনানী ১১",
    lat: 23.7937,
    lng: 90.4066,
    waitTime: "2-5 min",
    area: "Banani",
  },
  {
    id: 10,
    name: "Jigatola",
    namebn: "জিগাতলা",
    lat: 23.7384,
    lng: 90.3745,
    waitTime: "1-3 min",
    area: "Dhanmondi",
  },
  {
    id: 11,
    name: "Shyamoli",
    namebn: "শ্যামলী",
    lat: 23.7697,
    lng: 90.3576,
    waitTime: "2-5 min",
    area: "Shyamoli",
  },
  {
    id: 12,
    name: "Uttara Sector 11",
    namebn: "উত্তরা সেক্টর ১১",
    lat: 23.8759,
    lng: 90.3936,
    waitTime: "4-10 min",
    area: "Uttara",
  },
  {
    id: 13,
    name: "Rayer Bazar",
    namebn: "রায়ের বাজার",
    lat: 23.7541,
    lng: 90.3594,
    waitTime: "3-6 min",
    area: "Mohammadpur",
  },
  {
    id: 14,
    name: "Chawkbazar",
    namebn: "চকবাজার",
    lat: 23.7215,
    lng: 90.402,
    waitTime: "1-2 min",
    area: "Old Dhaka",
  },
  {
    id: 15,
    name: "Karwan Bazar",
    namebn: "কারওয়ান বাজার",
    lat: 23.7513,
    lng: 90.393,
    waitTime: "2-4 min",
    area: "Tejgaon",
  },
  {
    id: 16,
    name: "Shahbag",
    namebn: "শাহবাগ",
    lat: 23.7388,
    lng: 90.3958,
    waitTime: "1-3 min",
    area: "Shahbag",
  },
  {
    id: 17,
    name: "Azimpur",
    namebn: "আজিমপুর",
    lat: 23.726,
    lng: 90.3869,
    waitTime: "2-4 min",
    area: "Lalbagh",
  },
  {
    id: 18,
    name: "Paltan",
    namebn: "পল্টন",
    lat: 23.733,
    lng: 90.415,
    waitTime: "2-5 min",
    area: "Motijheel",
  },
  {
    id: 19,
    name: "Elephant Road",
    namebn: "এলিফ্যান্ট রোড",
    lat: 23.7401,
    lng: 90.3868,
    waitTime: "1-3 min",
    area: "New Market",
  },
  {
    id: 20,
    name: "Mirpur 1",
    namebn: "মিরপুর ১",
    lat: 23.7938,
    lng: 90.3584,
    waitTime: "2-5 min",
    area: "Mirpur",
  },
  {
    id: 21,
    name: "Mirpur 2",
    namebn: "মিরপুর ২",
    lat: 23.801,
    lng: 90.3612,
    waitTime: "2-4 min",
    area: "Mirpur",
  },
  {
    id: 22,
    name: "Agargaon",
    namebn: "আগারগাঁও",
    lat: 23.7773,
    lng: 90.38,
    waitTime: "3-6 min",
    area: "Agargaon",
  },
  {
    id: 23,
    name: "Tejgaon",
    namebn: "তেজগাঁও",
    lat: 23.7617,
    lng: 90.402,
    waitTime: "2-5 min",
    area: "Tejgaon",
  },
  {
    id: 24,
    name: "Malibagh",
    namebn: "মালিবাগ",
    lat: 23.7489,
    lng: 90.421,
    waitTime: "2-4 min",
    area: "Malibagh",
  },
  {
    id: 25,
    name: "Rampura",
    namebn: "রামপুরা",
    lat: 23.758,
    lng: 90.435,
    waitTime: "2-5 min",
    area: "Rampura",
  },
  {
    id: 26,
    name: "Badda",
    namebn: "বাড্ডা",
    lat: 23.7799,
    lng: 90.428,
    waitTime: "3-6 min",
    area: "Badda",
  },
  {
    id: 27,
    name: "Khilgaon",
    namebn: "খিলগাঁও",
    lat: 23.742,
    lng: 90.433,
    waitTime: "2-5 min",
    area: "Khilgaon",
  },
  {
    id: 28,
    name: "Basabo",
    namebn: "বাসাবো",
    lat: 23.735,
    lng: 90.438,
    waitTime: "3-6 min",
    area: "Sabujbagh",
  },
  {
    id: 29,
    name: "Jatrabari",
    namebn: "যাত্রাবাড়ী",
    lat: 23.713,
    lng: 90.435,
    waitTime: "2-4 min",
    area: "Jatrabari",
  },
  {
    id: 30,
    name: "Demra",
    namebn: "ডেমরা",
    lat: 23.705,
    lng: 90.46,
    waitTime: "4-8 min",
    area: "Demra",
  },
  {
    id: 31,
    name: "Postogola",
    namebn: "পোস্তগোলা",
    lat: 23.705,
    lng: 90.425,
    waitTime: "3-6 min",
    area: "Jatrabari",
  },
  {
    id: 32,
    name: "Gulistan",
    namebn: "গুলিস্তান",
    lat: 23.7237,
    lng: 90.4148,
    waitTime: "1-2 min",
    area: "Old Dhaka",
  },
  {
    id: 33,
    name: "Wari",
    namebn: "ওয়ারী",
    lat: 23.718,
    lng: 90.418,
    waitTime: "2-4 min",
    area: "Old Dhaka",
  },
  {
    id: 34,
    name: "Narinda",
    namebn: "নারিন্দা",
    lat: 23.716,
    lng: 90.41,
    waitTime: "2-5 min",
    area: "Old Dhaka",
  },
  {
    id: 35,
    name: "Gandaria",
    namebn: "গেন্ডারিয়া",
    lat: 23.71,
    lng: 90.415,
    waitTime: "2-4 min",
    area: "Old Dhaka",
  },
  {
    id: 36,
    name: "Sutrapur",
    namebn: "সূত্রাপুর",
    lat: 23.714,
    lng: 90.408,
    waitTime: "2-5 min",
    area: "Old Dhaka",
  },
  {
    id: 37,
    name: "Lalbagh",
    namebn: "লালবাগ",
    lat: 23.7198,
    lng: 90.3882,
    waitTime: "2-4 min",
    area: "Lalbagh",
  },
  {
    id: 38,
    name: "Hazaribagh",
    namebn: "হাজারীবাগ",
    lat: 23.723,
    lng: 90.378,
    waitTime: "2-5 min",
    area: "Lalbagh",
  },
  {
    id: 39,
    name: "Kamrangirchar",
    namebn: "কামরাঙ্গীরচর",
    lat: 23.71,
    lng: 90.375,
    waitTime: "3-6 min",
    area: "Kamrangirchar",
  },
  {
    id: 40,
    name: "Keraniganj",
    namebn: "কেরানীগঞ্জ",
    lat: 23.698,
    lng: 90.385,
    waitTime: "4-8 min",
    area: "Keraniganj",
  },
  {
    id: 41,
    name: "Zigatola",
    namebn: "জিগাতলা বাসস্ট্যান্ড",
    lat: 23.737,
    lng: 90.372,
    waitTime: "1-3 min",
    area: "Dhanmondi",
  },
  {
    id: 42,
    name: "Kalabagan",
    namebn: "কলাবাগান",
    lat: 23.743,
    lng: 90.38,
    waitTime: "1-3 min",
    area: "Dhanmondi",
  },
  {
    id: 43,
    name: "Panthapath",
    namebn: "পান্থপথ",
    lat: 23.751,
    lng: 90.387,
    waitTime: "2-4 min",
    area: "Tejgaon",
  },
  {
    id: 44,
    name: "Hatirpool",
    namebn: "হাতিরপুল",
    lat: 23.745,
    lng: 90.391,
    waitTime: "1-3 min",
    area: "Dhanmondi",
  },
  {
    id: 45,
    name: "Eskaton",
    namebn: "ইস্কাটন",
    lat: 23.748,
    lng: 90.398,
    waitTime: "2-4 min",
    area: "Ramna",
  },
  {
    id: 46,
    name: "Nayapaltan",
    namebn: "নয়াপল্টন",
    lat: 23.736,
    lng: 90.413,
    waitTime: "1-3 min",
    area: "Motijheel",
  },
  {
    id: 47,
    name: "Kakrail",
    namebn: "কাকরাইল",
    lat: 23.74,
    lng: 90.408,
    waitTime: "2-4 min",
    area: "Ramna",
  },
  {
    id: 48,
    name: "Maghbazar",
    namebn: "মগবাজার",
    lat: 23.749,
    lng: 90.408,
    waitTime: "2-5 min",
    area: "Ramna",
  },
  {
    id: 49,
    name: "Shantinagar",
    namebn: "শান্তিনগর",
    lat: 23.741,
    lng: 90.42,
    waitTime: "2-4 min",
    area: "Motijheel",
  },
  {
    id: 50,
    name: "Gopibagh",
    namebn: "গোপীবাগ",
    lat: 23.731,
    lng: 90.422,
    waitTime: "2-5 min",
    area: "Motijheel",
  },
];
